sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 8.142.73.253
    port: 3306
    database: sky_take_out
    username: root
    password: CHD-lab-602

  redis:
    host: localhost
    port: 6379
    password: 123456

  wechat:
    appid: wxcbd232350a706002
    secret: 854a057c9ba39e255cef3c24b9d5daec
